### ISSUE TITLE
cec 3.0.1

### ISSUE THREAD

**Issue by avenantsoftware** [iKenndac/Couch-Slouch#3]
is this project abbandoned?

would be nice to have the latest cec 3.0.1 in couch slouch

**Comment by iKenndac** [comment]
The project isn't abandoned - it's been working perfectly for me for over a year and I don't get many bug reports, so there's not much to do! Thanks for the nudge, though - I'll get libCEC updated.

**Comment by spambus** [comment]
cool, thanks

**Comment by spambus** [comment]
btw I tried adding the latest cec myself, first I just replaced the libcec folder in your xcode project with the newst libcec, but that didn't work, because they changed alot in cec, other directories etc., then I just copied over the newer cec over the exisiting one replacing files and it compiles, but I don't know if it uses the newer files lol, is there a way to check wich cec version is running in Couck Slouch when it's running?

**Comment by iKenndac** [comment]
The About window in Couch Slouch shows the libCEC version.

**Comment by spambus** [comment]
that only says libCEC 2014, no version number

**Comment by iKenndac** [comment]
2014 = 2.1.4.

**Comment by spambus** [comment]
ok, then copying over the newer folder over the existing folder didn't work lol
